<?php
/**
 * @file
 * Drupal hooks and functions for admin_denied.
 */

/**
 * Implements hook_cron().
 */
function admin_denied_cron() {
  /*
   * Generate a new random username that does not already exist. This loop
   * will exit if a generated username is NOT found.
   *
   * @See user_account_form_validate()
   */
  do {
    $username = user_password(16);
  } while ((bool) db_select('users')->fields('users', array('uid'))->condition('uid', 0, '<>')->condition('name', db_like($username), 'LIKE')->range(0, 1)->execute()->fetchField());

  // Set the uid 1 username and password to random strings.
  $result = db_update('users')
    ->fields(array(
      'name' => $username,
      'pass' => user_password(16),
    ))
    ->condition('uid', 1)
    ->execute();

  // Write an entry to the watchdog log.
  if ($result) {
    watchdog('admin_denied', 'Randomised the username and password for user 1', array(), WATCHDOG_NOTICE);
  }
  else {
    watchdog('admin_denied', 'Failed to randomise the username and password for user 1', array(), WATCHDOG_ERROR);
  }
}
