user_password_randomizer.settings:
  type: config_object
  label: 'User Password Randomizer settings'
  mapping:
    randomize_username:
      type: boolean
      label: 'Whether to randomizer username'
    username_pattern:
      type: string
      label: 'Username pattern'
    update_interval:
      type: int
      label: 'Update interval'
